services:
    ludwig:
        build:
            context: ../../
            dockerfile: docker/development/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ../../:/app
        depends_on:
            - db
        environment:
            - DB_ENGINE=${DB_ENGINE}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        env_file:
            - .env

    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        env_file:
            - .env
        ports:
            - "5432:5432"

volumes:
    postgres_data:
