# Generated by Django 5.2 on 2025-05-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialogue",
            name="id",
            field=models.CharField(
                default="l8Q1qiMLDSNRxW9z",
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
