# Generated by Django 5.2 on 2025-05-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogues", "0002_alter_dialogue_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialogue",
            name="id",
            field=models.CharField(
                default="XqyfGhZTAa",
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
