# Generated by Django 5.2 on 2025-05-10 04:43

import ludwig.dialogues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogues", "0004_alter_dialogue_id_alter_dialogue_is_open_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dialogue",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterField(
            model_name="dialogue",
            name="id",
            field=models.CharField(
                default=ludwig.dialogues.models.generate_unique_id,
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
