# Generated by Django 5.2 on 2025-05-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogues", "0005_alter_dialogue_options_alter_dialogue_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialogue",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
    ]
