# Generated by Django 5.2 on 2025-05-21 14:07

import ludwig.dialogues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogues", "0006_alter_dialogue_is_visible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogue",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(ludwig.dialogues.models.get_sentinel_user),
                related_name="created_dialogues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
