# Generated by Django 5.2 on 2025-05-21 14:12

import ludwig.dialogues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogues", "0007_dialogue_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dialogue",
            name="created_by",
        ),
        migrations.AddField(
            model_name="dialogue",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(ludwig.dialogues.models.get_sentinel_user),
                related_name="authored_dialogues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
